artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/853083639859914893/85402b03d5754ce7a40061d095c6da1a/artifacts
end_time: 1782594609976
entry_point_name: ''
experiment_id: '853083639859914893'
lifecycle_stage: active
run_id: 85402b03d5754ce7a40061d095c6da1a
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782593662938
status: 3
tags: []
user_id: root
