artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/853083639859914893/cef41ca0dba34cb9a7cba9e9edac55ab/artifacts
end_time: 1782612614958
entry_point_name: ''
experiment_id: '853083639859914893'
lifecycle_stage: active
run_id: cef41ca0dba34cb9a7cba9e9edac55ab
run_name: gradient_reversal_gan
source_name: ''
source_type: 4
source_version: ''
start_time: 1782612152611
status: 3
tags: []
user_id: root
