artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/853083639859914893/a2febe1a6e4141609cc90aaee5a465c7/artifacts
end_time: null
entry_point_name: ''
experiment_id: '853083639859914893'
lifecycle_stage: active
run_id: a2febe1a6e4141609cc90aaee5a465c7
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782574217666
status: 1
tags: []
user_id: root
