artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/853083639859914893/b70a70b578184d159cabf4b8ca85075b/artifacts
end_time: 1782590439806
entry_point_name: ''
experiment_id: '853083639859914893'
lifecycle_stage: active
run_id: b70a70b578184d159cabf4b8ca85075b
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782589481997
status: 3
tags: []
user_id: root
