artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/853083639859914893/82e9e9f888ba4ca18e4b3404fe289622/artifacts
end_time: 1782575762055
entry_point_name: ''
experiment_id: '853083639859914893'
lifecycle_stage: active
run_id: 82e9e9f888ba4ca18e4b3404fe289622
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782575072375
status: 3
tags: []
user_id: root
