artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/853083639859914893/1f2c7daaee07443992c79154cc302b01/artifacts
end_time: 1782652229173
entry_point_name: ''
experiment_id: '853083639859914893'
lifecycle_stage: active
run_id: 1f2c7daaee07443992c79154cc302b01
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782651182277
status: 3
tags: []
user_id: root
