artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/853083639859914893/0a8be2ea206547ccacad3d99b5a7da7d/artifacts
end_time: 1782593618929
entry_point_name: ''
experiment_id: '853083639859914893'
lifecycle_stage: active
run_id: 0a8be2ea206547ccacad3d99b5a7da7d
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782592312023
status: 3
tags: []
user_id: root
