artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/853083639859914893/cf9740f90d7d4dcf9e1a6db497cdd516/artifacts
end_time: 1782587605598
entry_point_name: ''
experiment_id: '853083639859914893'
lifecycle_stage: active
run_id: cf9740f90d7d4dcf9e1a6db497cdd516
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782586190270
status: 3
tags: []
user_id: root
