artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/853083639859914893/56711c4ebde04e0783a2a8cc9febbb23/artifacts
end_time: 1782610610627
entry_point_name: ''
experiment_id: '853083639859914893'
lifecycle_stage: active
run_id: 56711c4ebde04e0783a2a8cc9febbb23
run_name: gradient_reversal_gan
source_name: ''
source_type: 4
source_version: ''
start_time: 1782610374474
status: 3
tags: []
user_id: root
