artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/853083639859914893/a11e4478206b46c2a74a9915c6c773ce/artifacts
end_time: 1782599600823
entry_point_name: ''
experiment_id: '853083639859914893'
lifecycle_stage: active
run_id: a11e4478206b46c2a74a9915c6c773ce
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782598320951
status: 3
tags: []
user_id: root
